# Importing the packages and data

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
from sklearn.metrics import r2_score, mean_squared_error

from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler

from texttable import Texttable
import latextable

In [3]:
import sys
sys.path.insert(1, '../sar_dirichlet')
import dirichlet_regression

In [4]:
from func_test import cos_similarity, rmse_aitchison

# Loading Dataset

In [5]:
arctic = pd.read_csv('Data Dirichlet/ArcticLake.csv')

In [6]:
Y_arctic = arctic.iloc[:,:3]
X_arctic = arctic.iloc[:,3]

In [7]:
Y_arctic = np.array(Y_arctic)

In [8]:
X_arctic = np.array([[j] for j in X_arctic])

In [9]:
Z_arctic = np.ones(len(X_arctic)).reshape((39,1))

In [10]:
n_features = 1
n_classes = 3

In [11]:
X = np.array(X_arctic)
Y = np.array(Y_arctic)

X = StandardScaler().fit(X).transform(X)

In [12]:
Z = Z_arctic
gamma_0 = [0.]

In [13]:
n,K = X.shape
J = Y.shape[1]

# Order 1

In [47]:
distance_matrix = scipy.spatial.distance_matrix(X_arctic,X_arctic)
W_arctic_cont = np.zeros(np.shape(distance_matrix))
W_arctic_cont[distance_matrix < 20] = 1
# replace the 1 on the diagonal by 0
np.fill_diagonal(W_arctic_cont,0)
# scaling the matrix, so that the sum of each row is 1
W_arctic_cont = W_arctic_cont/W_arctic_cont.sum(axis=1)[:,None]

In [48]:
print('Average number of neighbours in W_arctic_cont :', np.mean(np.sum(W_arctic_cont>0, axis=1)) )

Average number of neighbours in W_arctic_cont : 13.794871794871796


In [49]:
neighbors = NearestNeighbors(n_neighbors=15).fit(X)
W_arctic_dist = neighbors.kneighbors_graph(X,mode='distance').toarray()
W_arctic_dist[W_arctic_dist>0] = 1/W_arctic_dist[W_arctic_dist>0]
W_arctic_dist = W_arctic_dist/W_arctic_dist.sum(axis=1)[:,None]

# Inference tests

In [50]:
%%time
dirichRegressor = dirichlet_regression.dirichletRegressor()
dirichRegressor.fit(X, Y, parametrization='alternative', gamma_0 = gamma_0, Z=Z)

Optimization terminated successfully.
Wall time: 12.7 ms


In [51]:
ll_non_spatial_1 = dirichlet_regression.dirichlet_loglikelihood(dirichRegressor.mu,dirichRegressor.phi,Y)
ll_non_spatial_1

77.72809940035866

In [52]:
dirichRegressor.beta

array([[1.044688  , 0.42575255],
       [1.08824776, 1.55837907]])

In [53]:
dirichRegressor.compute_hessian(X,Y,Z)

In [54]:
np.diag(dirichRegressor.hess)

array([-148.43568465, -115.49153564, -147.58486218, -128.28546153,
        -45.43222872])

In [55]:
cov = np.linalg.pinv(-dirichRegressor.hess)

In [56]:
# standard errors
np.sqrt(np.diag(cov))

array([0.13184403, 0.14043332, 0.15368295, 0.16312287, 0.16226657])

In [57]:
dirichRegressor.gamma[0]

2.626560915133771

In [58]:
# z-values : \hat{\beta} / se
print(f"z-values for beta : {dirichRegressor.beta.flatten()/np.sqrt(np.diag(cov))[:-1]}")
print(f"z-values for gamma : {dirichRegressor.gamma[0] / np.sqrt(np.diag(cov))[-1]}")

z-values for beta : [7.92366543 3.03170598 7.08112233 9.55340638]
z-values for gamma : 16.18670416392397


## Spatial contiguity order 1

In [59]:
%%time
dirichRegressor_sc_1 = dirichlet_regression.dirichletRegressor(spatial=True)
dirichRegressor_sc_1.fit(X, Y, W=W_arctic_cont, parametrization='alternative', gamma_0 = gamma_0, Z=Z)

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
Wall time: 60.3 ms


In [60]:
ll_cont_1 = dirichlet_regression.dirichlet_loglikelihood(dirichRegressor_sc_1.mu,dirichRegressor_sc_1.phi,Y)
ll_cont_1

80.23047417467671

In [61]:
dirichRegressor_sc_1.inference(X, Y, Z, W_arctic_cont, display=True)

-----
Estimated parameter beta_11 = 2.1055, se = 0.787, CI 95% = [0.5629 ; 3.648],  p-value = 0.0075
-----
Estimated parameter beta_12 = 0.8614, se = 0.4054, CI 95% = [0.0668 ; 1.656],  p-value = 0.0336
-----
Estimated parameter beta_21 = 2.1071, se = 0.7485, CI 95% = [0.6401 ; 3.5741],  p-value = 0.0049
-----
Estimated parameter beta_22 = 2.9938, se = 1.0259, CI 95% = [0.983 ; 5.0045],  p-value = 0.0035
-----
Estimated parameter gamma_1 = 2.6993, se = 0.1643, CI 95% = [2.3773 ; 3.0213],  p-value = 0.0
-----
Estimated parameter rho = -1.0, se = 0.7094, CI 95% = [-2.3904 ; 0.3904],  p-value = 0.1586


## Spatial contiguity order 2

In [62]:
X = np.array(X_arctic)
X = StandardScaler().fit(X).transform(X)

In [63]:
X_2 = np.ones((39,2))
X_2[:,0] = X[:,0]
X_2[:,1] = X[:,0]**2

In [64]:
%%time
dirichRegressor_sc_2 = dirichlet_regression.dirichletRegressor(spatial=True)
dirichRegressor_sc_2.fit(X_2, Y, W=W_arctic_cont, parametrization='alternative', gamma_0 = gamma_0, Z=Z)

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
Wall time: 92.7 ms


In [65]:
ll_cont_2 = dirichlet_regression.dirichlet_loglikelihood(dirichRegressor_sc_2.mu,dirichRegressor_sc_2.phi,Y)
ll_cont_2

91.90996930125503

In [66]:
dirichRegressor_sc_2.inference(X_2, Y, Z, W_arctic_cont, display=True)

-----
Estimated parameter beta_11 = 2.1841, se = 0.6908, CI 95% = [0.8301 ; 3.5381],  p-value = 0.0016
-----
Estimated parameter beta_12 = 1.496, se = 0.4336, CI 95% = [0.6462 ; 2.3458],  p-value = 0.0006
-----
Estimated parameter beta_21 = 1.6135, se = 0.5176, CI 95% = [0.5989 ; 2.6281],  p-value = 0.0018
-----
Estimated parameter beta_22 = 2.6542, se = 0.8577, CI 95% = [0.973 ; 4.3353],  p-value = 0.002
-----
Estimated parameter beta_31 = -0.5534, se = 0.1654, CI 95% = [-0.8775 ; -0.2292],  p-value = 0.0008
-----
Estimated parameter beta_32 = -0.9497, se = 0.2428, CI 95% = [-1.4255 ; -0.4739],  p-value = 0.0001
-----
Estimated parameter gamma_1 = 2.963, se = 0.1588, CI 95% = [2.6518 ; 3.2741],  p-value = 0.0
-----
Estimated parameter rho = -0.6132, se = 0.5722, CI 95% = [-1.7347 ; 0.5083],  p-value = 0.2838


## Spatial distance

In [73]:
neighbors = NearestNeighbors(n_neighbors=15).fit(X)
W_arctic_dist = neighbors.kneighbors_graph(X,mode='distance').toarray()
W_arctic_dist[W_arctic_dist>0] = 1/W_arctic_dist[W_arctic_dist>0]
W_arctic_dist = W_arctic_dist/W_arctic_dist.sum(axis=1)[:,None]

In [74]:
%%time
dirichRegressor_sd = dirichlet_regression.dirichletRegressor(spatial=True)
dirichRegressor_sd.fit(X, Y, W=W_arctic_dist, parametrization='alternative', gamma_0 = gamma_0, Z=Z)

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
Wall time: 44.8 ms


In [75]:
dirichlet_regression.dirichlet_loglikelihood(dirichRegressor_sd.mu,dirichRegressor_sd.phi,Y)

77.78705654561672

In [76]:
dirichRegressor_sd.compute_hessian(X,Y,Z,W_arctic_dist)

In [77]:
np.diag(dirichRegressor_sd.hess)

array([-307.07787262, -238.53889951, -289.53113933, -250.00278718,
        -45.42456056, -265.1925039 ])

In [78]:
dirichRegressor_sd.beta

array([[0.73129158, 0.30414738],
       [0.76762519, 1.10658029]])

In [79]:
dirichRegressor_sd.rho

0.30507395247435143

In [80]:
dirichRegressor_sd.inference(X, Y, Z, W_arctic_cont, display=True)

-----
Estimated parameter beta_11 = 0.7313, se = 0.8248, CI 95% = [-0.8853 ; 2.3479],  p-value = 0.3753
-----
Estimated parameter beta_12 = 0.3041, se = 0.3345, CI 95% = [-0.3514 ; 0.9597],  p-value = 0.3632
-----
Estimated parameter beta_21 = 0.7676, se = 0.8467, CI 95% = [-0.892 ; 2.4272],  p-value = 0.3646
-----
Estimated parameter beta_22 = 1.1066, se = 1.1959, CI 95% = [-1.2374 ; 3.4506],  p-value = 0.3548
-----
Estimated parameter gamma_1 = 2.6244, se = 0.1623, CI 95% = [2.3064 ; 2.9425],  p-value = 0.0
-----
Estimated parameter rho = 0.3051, se = 0.796, CI 95% = [-1.2551 ; 1.8653],  p-value = 0.7015


In [87]:
ll_dist_1 = dirichlet_regression.dirichlet_loglikelihood(dirichRegressor_sd.mu,dirichRegressor_sd.phi,Y)
ll_dist_1

77.78705654561672

### Order 2

In [81]:
%%time
dirichRegressor_sd_2 = dirichlet_regression.dirichletRegressor(spatial=True)
dirichRegressor_sd_2.fit(X_2, Y, W=W_arctic_dist, parametrization='alternative', gamma_0 = gamma_0, Z=Z)

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
Wall time: 92.8 ms


In [82]:
dirichRegressor_sd_2.inference(X_2, Y, Z, W_arctic_cont, display=True)

-----
Estimated parameter beta_11 = 0.9316, se = 0.5835, CI 95% = [-0.2122 ; 2.0753],  p-value = 0.1104
-----
Estimated parameter beta_12 = 0.719, se = 0.3483, CI 95% = [0.0364 ; 1.4017],  p-value = 0.039
-----
Estimated parameter beta_21 = 0.6671, se = 0.3981, CI 95% = [-0.1131 ; 1.4473],  p-value = 0.0938
-----
Estimated parameter beta_22 = 1.0877, se = 0.6641, CI 95% = [-0.2139 ; 2.3893],  p-value = 0.1014
-----
Estimated parameter beta_31 = -0.3135, se = 0.1202, CI 95% = [-0.549 ; -0.0779],  p-value = 0.0091
-----
Estimated parameter beta_32 = -0.511, se = 0.1866, CI 95% = [-0.8767 ; -0.1454],  p-value = 0.0062
-----
Estimated parameter gamma_1 = 2.9459, se = 0.1609, CI 95% = [2.6306 ; 3.2612],  p-value = 0.0
-----
Estimated parameter rho = 0.3881, se = 0.4751, CI 95% = [-0.543 ; 1.3193],  p-value = 0.4139


In [88]:
ll_dist_2 = dirichlet_regression.dirichlet_loglikelihood(dirichRegressor_sd_2.mu,dirichRegressor_sd_2.phi,Y)
ll_dist_2

91.33665551227668

# LR tests

In [83]:
from scipy.stats import chi2

In [84]:
def lr_test_rho(ll_restricted, ll_unrestricted, df=1):
    LR = 2 * (ll_unrestricted - ll_restricted)
    p_value = 1 - chi2.cdf(LR, df)
    return LR, p_value

In [91]:
lr_test_rho(ll_non_spatial_1, ll_cont_1)

(5.004749548636113, 0.02527786063060833)

In [89]:
lr_test_rho(ll_non_spatial_1, ll_dist_1)

(0.11791429051612567, 0.7313077119132385)

In [71]:
%%time
dirichRegressor_2 = dirichlet_regression.dirichletRegressor()
dirichRegressor_2.fit(X_2, Y, parametrization='alternative', gamma_0 = gamma_0, Z=Z)
ll_non_spatial_2 = dirichlet_regression.dirichlet_loglikelihood(dirichRegressor_2.mu,dirichRegressor_2.phi,Y)

Optimization terminated successfully.
Wall time: 6.96 ms


In [72]:
lr_test_rho(ll_non_spatial_2, ll_cont_2)

(1.259152535162258, 0.26181156508497183)

In [90]:
lr_test_rho(ll_non_spatial_2, ll_dist_2)

(0.11252495720555089, 0.7372876181057403)

# Multivariate Wald test

In [94]:
from texttable import Texttable
import latextable

In [93]:
from scipy.stats import chi2

def multivariate_wald_test(dirichlet_regressor, feature_index=None):
    """
    Perform multivariate Wald test for Dirichlet regression coefficients.
    
    Parameters
    ----------
    dirichlet_regressor : dirichletRegressor object
        Fitted spatial Dirichlet regression model
    feature_index : int or None
        Index of feature to test. If None, tests all features.
    
    Returns
    -------
    dict : Dictionary with test results for each feature
    """
    # Extract beta coefficients and covariance matrix
    n_samples = X.shape[0]
    beta = dirichlet_regressor.beta  # Shape: (K+1) x J, where K=n_features, J=n_classes-1
    cov_matrix = dirichlet_regressor.cov  # Covariance matrix
    
    # Get dimensions
    K_plus_1, J = beta.shape  # K+1 includes intercept
    #K = K_plus_1 - 1  # Number of features (excluding intercept)
    K = K_plus_1
    n_samples = X.shape[0]
    
    # Dictionary to store results
    results = {}
    
    # Determine which features to test
    if feature_index is not None:
        features_to_test = [feature_index]
    else:
        features_to_test = range(K)
    
    for k in features_to_test:
        # Extract the row for this feature across all classes
        # Note: beta index 0 is intercept, so feature k corresponds to row k+1
        beta_row = beta[k, :]  # Shape: (J,)
        
        # Extract the corresponding block from the covariance matrix
        # The covariance matrix is organized by stacking all parameters
        # Need to extract the right indices for this feature
        
        # Total parameters: (K+1) * J
        # Parameters are organized as: [beta_11, beta_12, ..., beta_1J, beta_21, ..., beta_KJ]
        
        # Calculate indices for this feature across all classes
        start_idx = (k) * J  # Skip intercept rows
        end_idx = start_idx + J
        indices = list(range(start_idx, end_idx))
        
        # Extract sub-covariance matrix for this feature
        V_k = cov_matrix[np.ix_(indices, indices)]  # Shape: J x J
        
        # Perform Wald test: W = beta^T * (V/n)^-1 * beta ~ chi2(J)
        #V_k_n = V_k / n_samples
        V_k_n = V_k
        #V_k_n = np.diag(V_k)
        
        try:
            # Calculate Wald statistic
            Wald = beta_row @ np.linalg.inv(V_k_n) @ beta_row
            #Wald = beta_row/V_k_n @ beta_row 
            #print("beta_row:", beta_row)
            #print("V_k:", V_k_n)
            #print("Wald:", Wald)
            #print('-----')
            
            # Calculate p-value
            p_value = 1 - chi2.cdf(Wald, J)
            
            results[X_names[k]] = {
                'Wald_statistic': Wald,
                'p_value': p_value,
                'degrees_of_freedom': J,
                'beta_values': beta_row
            }
            
        except np.linalg.LinAlgError:
            # Handle singular matrix
            results[f'feature_{k}'] = {
                'Wald_statistic': np.nan,
                'p_value': np.nan,
                'degrees_of_freedom': J,
                'beta_values': beta_row,
                'error': 'Singular covariance matrix'
            }
    
    return results

In [95]:
def display_results_wald_multivarie(wald_results):

    table = Texttable()
    table.set_deco(Texttable.HEADER)
    table.set_cols_align(["l", "r", "r", "r"])

    rows = [["Feature", "Wald Stat", "df", "p-value"]]
    for feat_name, res in wald_results.items():
        rows.append([
            feat_name,
            f"{res['Wald_statistic']:.3f}",
            res['degrees_of_freedom'],
            f"{res['p_value']:.6f}"
        ])

    table.add_rows(rows)
    print(table.draw())
    print("\n" + "="*60)

## Order 1

In [100]:
X_names = ['intercept', 'depth']

In [97]:
wald_results = multivariate_wald_test(dirichRegressor_sd)
display_results_wald_multivarie(wald_results)

 Feature    Wald Stat   df   p-value
intercept       0.827    2     0.661
depth           0.903    2     0.637



In [98]:
wald_results = multivariate_wald_test(dirichRegressor_sc_1)
display_results_wald_multivarie(wald_results)

 Feature    Wald Stat   df   p-value
intercept       7.273    2     0.026
depth           8.542    2     0.014



## Order 2

In [101]:
X_names = ['intercept', 'depth', 'depth^2']

In [102]:
wald_results = multivariate_wald_test(dirichRegressor_sd_2)
display_results_wald_multivarie(wald_results)

 Feature    Wald Stat   df   p-value
intercept       7.145    2     0.028
depth           2.830    2     0.243
depth^2         7.793    2     0.020



In [103]:
wald_results = multivariate_wald_test(dirichRegressor_sc_2)
display_results_wald_multivarie(wald_results)

 Feature    Wald Stat   df   p-value
intercept      11.906    2     0.003
depth           9.822    2     0.007
depth^2        15.894    2     0.000

