# Importing the packages and data

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
from sklearn.metrics import r2_score, mean_squared_error

from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler

from texttable import Texttable
import latextable

In [3]:
import sys
sys.path.insert(1, '../sar_dirichlet')
import dirichlet_regression

In [4]:
from func_test import cos_similarity, rmse_aitchison

In [5]:
scipy.__version__

'1.10.1'

# Loading Dataset

In [6]:
arctic = pd.read_csv('Data Dirichlet/ArcticLake.csv')

In [7]:
Y_arctic = arctic.iloc[:,:3]
X_arctic = arctic.iloc[:,3]

In [8]:
Y_arctic = np.array(Y_arctic)

In [9]:
X_arctic = np.array([[j] for j in X_arctic])

In [10]:
Z_arctic = np.ones(len(X_arctic)).reshape((39,1))

In [11]:
n_features = 1
n_classes = 3

In [12]:
X = np.array(X_arctic)
Y = np.array(Y_arctic)

X = StandardScaler().fit(X).transform(X)

In [13]:
Z = Z_arctic
gamma_0 = [0.]

In [14]:
n,K = X.shape
J = Y.shape[1]

# Order 1

In [15]:
distance_matrix = scipy.spatial.distance_matrix(X_arctic,X_arctic)
W_arctic_cont = np.zeros(np.shape(distance_matrix))
W_arctic_cont[distance_matrix < 28] = 1
# replace the 1 on the diagonal by 0
np.fill_diagonal(W_arctic_cont,0)
# scaling the matrix, so that the sum of each row is 1
W_arctic_cont = W_arctic_cont/W_arctic_cont.sum(axis=1)[:,None]

In [16]:
neighbors = NearestNeighbors(n_neighbors=29).fit(X)
W_arctic_dist = neighbors.kneighbors_graph(X,mode='distance').toarray()
W_arctic_dist[W_arctic_dist>0] = 1/W_arctic_dist[W_arctic_dist>0]
W_arctic_dist = W_arctic_dist/W_arctic_dist.sum(axis=1)[:,None]

# Inference tests

In [17]:
%%time
dirichRegressor = dirichlet_regression.dirichletRegressor()
dirichRegressor.fit(X, Y, parametrization='alternative', gamma_0 = gamma_0, Z=Z)

Optimization terminated successfully.
Wall time: 0 ns


In [50]:
ll_non_spatial_1 = dirichlet_regression.dirichlet_loglikelihood(dirichRegressor.mu,dirichRegressor.phi,Y)
ll_non_spatial_1

77.72809940035866

In [19]:
dirichRegressor.beta

array([[1.044688  , 0.42575255],
       [1.08824776, 1.55837907]])

In [20]:
dirichRegressor.compute_hessian(X,Y,Z)

In [21]:
np.diag(dirichRegressor.hess)

array([-148.43568465, -115.49153564, -147.58486218, -128.28546153,
        -45.43222872])

In [26]:
cov = np.linalg.pinv(-dirichRegressor.hess)

In [27]:
# standard errors
np.sqrt(np.diag(cov))

array([0.13184403, 0.14043332, 0.15368295, 0.16312287, 0.16226657])

In [23]:
dirichRegressor.gamma[0]

2.626560915133771

In [28]:
# z-values : \hat{\beta} / se
print(f"z-values for beta : {dirichRegressor.beta.flatten()/np.sqrt(np.diag(cov))[:-1]}")
print(f"z-values for gamma : {dirichRegressor.gamma[0] / np.sqrt(np.diag(cov))[-1]}")

z-values for beta : [7.92366543 3.03170598 7.08112233 9.55340638]
z-values for gamma : 16.18670416392397


## Spatial contiguity order 1

In [29]:
%%time
dirichRegressor_sc_1 = dirichlet_regression.dirichletRegressor(spatial=True)
dirichRegressor_sc_1.fit(X, Y, W=W_arctic_cont, parametrization='alternative', gamma_0 = gamma_0, Z=Z)

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
Wall time: 84.6 ms


In [51]:
ll_cont_1 = dirichlet_regression.dirichlet_loglikelihood(dirichRegressor_sc_1.mu,dirichRegressor_sc_1.phi,Y)
ll_cont_1

82.80759632870098

In [31]:
dirichRegressor_sc_1.inference(X, Y, Z, W_arctic_cont, display=True)

-----
Estimated parameter beta_11 = 2.1157, se = 0.6989, CI 95% = [0.7459 ; 3.4855],  p-value = 0.0025
-----
Estimated parameter beta_12 = 0.8629, se = 0.3743, CI 95% = [0.1292 ; 1.5967],  p-value = 0.0212
-----
Estimated parameter beta_21 = 1.9893, se = 0.5733, CI 95% = [0.8657 ; 3.113],  p-value = 0.0005
-----
Estimated parameter beta_22 = 2.851, se = 0.797, CI 95% = [1.2888 ; 4.4131],  p-value = 0.0003
-----
Estimated parameter gamma_1 = 2.7649, se = 0.1719, CI 95% = [2.4279 ; 3.1018],  p-value = 0.0
-----
Estimated parameter rho = -1.0, se = 0.6112, CI 95% = [-2.1979 ; 0.1979],  p-value = 0.1018


## Spatial contiguity order 2

In [32]:
X = np.array(X_arctic)
X = StandardScaler().fit(X).transform(X)

In [33]:
X_2 = np.ones((39,2))
X_2[:,0] = X[:,0]
X_2[:,1] = X[:,0]**2

In [34]:
%%time
dirichRegressor_sc_2 = dirichlet_regression.dirichletRegressor(spatial=True)
dirichRegressor_sc_2.fit(X_2, Y, W=W_arctic_cont, parametrization='alternative', gamma_0 = gamma_0, Z=Z)

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
Wall time: 154 ms


In [56]:
ll_cont_2 = dirichlet_regression.dirichlet_loglikelihood(dirichRegressor_sc_2.mu,dirichRegressor_sc_2.phi,Y)
ll_cont_2

93.59446117019026

In [35]:
dirichRegressor_sc_2.inference(X_2, Y, Z, W_arctic_cont, display=True)

-----
Estimated parameter beta_11 = 2.5315, se = 0.5854, CI 95% = [1.3843 ; 3.6788],  p-value = 0.0
-----
Estimated parameter beta_12 = 1.5709, se = 0.3489, CI 95% = [0.8872 ; 2.2547],  p-value = 0.0
-----
Estimated parameter beta_21 = 1.7783, se = 0.3833, CI 95% = [1.0271 ; 2.5295],  p-value = 0.0
-----
Estimated parameter beta_22 = 2.9749, se = 0.639, CI 95% = [1.7225 ; 4.2272],  p-value = 0.0
-----
Estimated parameter beta_31 = -0.4921, se = 0.1461, CI 95% = [-0.7785 ; -0.2056],  p-value = 0.0008
-----
Estimated parameter beta_32 = -0.8843, se = 0.1774, CI 95% = [-1.232 ; -0.5366],  p-value = 0.0
-----
Estimated parameter gamma_1 = 3.0092, se = 0.1593, CI 95% = [2.697 ; 3.3215],  p-value = 0.0
-----
Estimated parameter rho = -1.0, se = 0.5109, CI 95% = [-2.0013 ; 0.0013],  p-value = 0.0503


## LR test

In [53]:
from scipy.stats import chi2

In [48]:
def lr_test_rho(ll_restricted, ll_unrestricted, df=1):
    LR = 2 * (ll_unrestricted - ll_restricted)
    p_value = 1 - chi2.cdf(LR, df)
    return LR, p_value

In [54]:
lr_test_rho(ll_non_spatial_1, ll_cont_1)

(10.158993856684646, 0.0014359896904190261)

In [55]:
%%time
dirichRegressor_2 = dirichlet_regression.dirichletRegressor()
dirichRegressor_2.fit(X_2, Y, parametrization='alternative', gamma_0 = gamma_0, Z=Z)
ll_non_spatial_2 = dirichlet_regression.dirichlet_loglikelihood(dirichRegressor_2.mu,dirichRegressor_2.phi,Y)

Optimization terminated successfully.
Wall time: 0 ns


In [57]:
lr_test_rho(ll_non_spatial_2, ll_cont_2)

(4.628136273032709, 0.03145171094794674)

## Spatial distance

In [37]:
%%time
dirichRegressor_sd = dirichlet_regression.dirichletRegressor(spatial=True)
dirichRegressor_sd.fit(X, Y, W=W_arctic_dist, parametrization='alternative', gamma_0 = gamma_0, Z=Z)

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
Wall time: 84.6 ms


In [38]:
dirichlet_regression.dirichlet_loglikelihood(dirichRegressor_sd.mu,dirichRegressor_sd.phi,Y)

77.72859550588747

In [39]:
dirichRegressor_sd.compute_hessian(X,Y,Z,W_arctic_dist)

In [40]:
np.diag(dirichRegressor_sd.hess)

array([-142.72938033, -111.06633736, -142.93517552, -124.3206096 ,
        -45.43246597, -109.90484265])

In [41]:
dirichRegressor_sd.beta

array([[1.06451567, 0.4328314 ],
       [1.10685771, 1.58427968]])

In [42]:
dirichRegressor_sd.rho

-0.01988173139158971