# Importing the packages and data

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
from sklearn.metrics import r2_score, mean_squared_error

from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

from texttable import Texttable
import latextable

In [11]:
import sys
sys.path.insert(1, '../sar_dirichlet')
import dirichlet_regression

In [14]:
from func_test import cos_similarity, create_features_matrices

In [77]:
scipy.__version__

'1.4.1'

# With two features

In [8]:
n_features = 2
n_classes = 3

In [9]:
np.random.seed(21)

beta = np.array([[0.  , -1.6 , 1.],
                 [0.  , 1.8, -1.4],
                 [0.  , 1.4, -1.1 ]])

gamma_var = np.round(np.random.normal(size=(n_features)),2)

In [10]:
n_repeat = 100
#list_n_samples = [50,200,1000]
list_n_samples = [50,200]

# Tests

In [11]:
n_samples=200
rho=0.5
#np.random.seed(11)
cov_mat = np.array([[1., 0.1], [0.1, 1.]])
X,Z,W = create_features_matrices(n_samples,n_features,choice_W='random_distance',nneighbors=10, cov_mat=cov_mat)
Z = np.ones(n_samples).reshape(-1,1)
list_n_i = np.random.randint(1, high=100, size=n_samples)
M = np.identity(n_samples) - rho*W
mu = dirichlet_regression.compute_mu_spatial(X, beta, M)

In [12]:
Y = np.array([np.random.multinomial(list_n_i[i],mu[i])/list_n_i[i] for i in range(n_samples)])
Y = (Y*(n_samples-1)+1/n_classes)/n_samples

In [14]:
reg_test = dirichlet_regression.dirichletRegressor(spatial=False)
reg_test.fit(X, Y, parametrization='alternative', Z=Z, fit_intercept=False, verbose=0)

In [15]:
print(np.round(r2_score(Y,reg_test.mu),4))
print(np.round(cos_similarity(Y,reg_test.mu),4))
print(np.round(-(1/n_samples)*np.sum(Y*np.log(reg_test.mu)),4))
print(np.round(mean_squared_error(Y,reg_test.mu,squared=False),4))

0.6904
0.9701
0.5427
0.1139


In [16]:
reg_test = dirichlet_regression.dirichletRegressor(spatial=False)
reg_test.fit(X, Y, parametrization='alternative', Z=Z, fit_intercept=False, verbose=0, loss='crossentropy')

In [17]:
print(np.round(r2_score(Y,reg_test.mu),4))
print(np.round(cos_similarity(Y,reg_test.mu),4))
print(np.round(-(1/n_samples)*np.sum(Y*np.log(reg_test.mu)),4))
print(np.round(mean_squared_error(Y,reg_test.mu,squared=False),4))

0.8016
0.9787
0.4994
0.0892


In [18]:
reg_test = dirichlet_regression.dirichletRegressor(spatial=False)
reg_test.fit(X, Y, parametrization='alternative', Z=Z, fit_intercept=False, verbose=0, loss='crossentropy', size_samples=list_n_i)

In [19]:
print(np.round(r2_score(Y,reg_test.mu),4))
print(np.round(cos_similarity(Y,reg_test.mu),4))
print(np.round(-(1/n_samples)*np.sum(Y*np.log(reg_test.mu)),4))
print(np.round(mean_squared_error(Y,reg_test.mu,squared=False),4))

0.7955
0.9781
0.5001
0.0903


In [204]:
reg_test = dirichlet_regression.dirichletRegressor(spatial=True)
reg_test.fit(X, Y, parametrization='alternative', Z=Z, W=W, fit_intercept=False, verbose=0)

In [205]:
print(reg_test.beta-beta[:,1:])
print(reg_test.rho)

[[ 0.0871204  -0.01669151]
 [-0.0875131   0.03574297]
 [-0.06662853  0.02900188]]
0.5006343124747678


In [206]:
print(np.round(r2_score(Y,reg_test.mu),5))
print(np.round(cos_similarity(Y,reg_test.mu),5))
print(np.round(-(1/n_samples)*np.sum(Y*np.log(reg_test.mu)),5))
print(np.round(mean_squared_error(Y,reg_test.mu,squared=False),5))

0.99962
0.99997
0.47482
0.00336


In [207]:
reg_test = dirichlet_regression.dirichletRegressor(spatial=True)
reg_test.fit(X, Y, parametrization='alternative', Z=Z, W=W, fit_intercept=False, verbose=0, loss='crossentropy')

In [208]:
print(reg_test.beta-beta[:,1:])
print(reg_test.rho)

[[ 0.11989243 -0.01780403]
 [-0.12151223  0.04141683]
 [-0.09275043  0.0334047 ]]
0.5008757547010351


In [209]:
print(np.round(r2_score(Y,reg_test.mu),5))
print(np.round(cos_similarity(Y,reg_test.mu),5))
print(np.round(-(1/n_samples)*np.sum(Y*np.log(reg_test.mu)),5))
print(np.round(mean_squared_error(Y,reg_test.mu,squared=False),5))

0.99939
0.99996
0.4748
0.00423


In [201]:
reg_test = dirichlet_regression.dirichletRegressor(spatial=True)
reg_test.fit(X, Y, parametrization='alternative', Z=Z, W=W, fit_intercept=False, verbose=0, loss='crossentropy', size_samples=list_n_i)

In [202]:
print(reg_test.beta-beta[:,1:])
print(reg_test.rho)

[[ 0.13179459 -0.02504934]
 [-0.12533287  0.04683481]
 [-0.0974142   0.03753615]]
0.5033170308840984


In [191]:
print(np.round(r2_score(Y,reg_test.mu),5))
print(np.round(cos_similarity(Y,reg_test.mu),5))
print(np.round(-(1/n_samples)*np.sum(Y*np.log(reg_test.mu)),5))
print(np.round(mean_squared_error(Y,reg_test.mu,squared=False),5))

0.99933
0.99995
0.47481
0.00449


# rho=0.1

In [10]:
rho=0.1

In [36]:
%%time
list_solutions_spatial = []
list_solutions_no_spatial = []
list_solutions_ce_spatial = []
list_solutions_ce_no_spatial = []
list_r2_spatial, list_r2_no_spatial, list_r2_ce_spatial, list_r2_ce_no_spatial = [], [], [], []
list_rmse_spatial, list_rmse_no_spatial, list_rmse_ce_spatial, list_rmse_ce_no_spatial = [], [], [], []
list_crossentropy_spatial, list_crossentropy_no_spatial, list_crossentropy_ce_spatial, list_crossentropy_ce_no_spatial = [], [], [], []
list_similarity_spatial, list_similarity_no_spatial, list_similarity_ce_spatial, list_similarity_ce_no_spatial = [], [], [], []


seed=0

for i in range(len(list_n_samples)):
    n_samples = list_n_samples[i]
    
    true_params = np.concatenate([beta.flatten(),gamma_var, [rho]])
    
    solutions_spatial_temp = []
    solutions_no_spatial_temp = []
    solutions_ce_spatial_temp = []
    solutions_ce_no_spatial_temp = []
    temp_r2_spatial, temp_r2_no_spatial, temp_r2_ce_spatial, temp_r2_ce_no_spatial = [], [], [], []
    temp_rmse_spatial, temp_rmse_no_spatial, temp_rmse_ce_spatial, temp_rmse_ce_no_spatial = [], [], [], []
    temp_crossentropy_spatial, temp_crossentropy_no_spatial, temp_crossentropy_ce_spatial, temp_crossentropy_ce_no_spatial = [], [], [], []
    temp_similarity_spatial, temp_similarity_no_spatial, temp_similarity_ce_spatial, temp_similarity_ce_no_spatial = [], [], [], []
    for _ in range(n_repeat):
        np.random.seed(seed)
        
        X,Z,W = create_features_matrices(n_samples,n_features,choice_W='random_distance',nneighbors=10)
        Z[:,0] = 1
        #les n_i ne devraient pas bouger, il faut les fixer comme pour les betas
        list_n_i = np.random.randint(100, high=10000, size=n_samples)
        M = np.identity(n_samples) - rho*W
        mu = dirichlet_regression.compute_mu_spatial(X, beta, M)
        Y = np.array([np.random.multinomial(list_n_i[i],mu[i])/list_n_i[i] for i in range(n_samples)])
        Y = (Y*(n_samples-1)+1/n_classes)/n_samples

        try:
            reg_spatial = dirichlet_regression.dirichletRegressor(spatial=True)
            reg_spatial.fit(X, Y, parametrization='alternative', Z=Z, W=W, fit_intercept=False, verbose=0)
            solutions_spatial_temp.append(np.concatenate([reg_spatial.beta.flatten(),reg_spatial.gamma,[reg_spatial.rho]]))
            temp_r2_spatial.append(r2_score(Y,reg_spatial.mu))
            temp_rmse_spatial.append(mean_squared_error(Y,reg_spatial.mu,squared=False))
            temp_similarity_spatial.append(cos_similarity(Y,reg_spatial.mu))
            temp_crossentropy_spatial.append(-(1/n_samples)*np.sum(Y*np.log(reg_spatial.mu)))
            
            reg_no_spatial = dirichlet_regression.dirichletRegressor(spatial=False)
            reg_no_spatial.fit(X, Y, parametrization='alternative', Z=Z, fit_intercept=False, verbose=0)
            solutions_no_spatial_temp.append(np.concatenate([reg_no_spatial.beta.flatten(),reg_no_spatial.gamma]))
            temp_r2_no_spatial.append(r2_score(Y,reg_no_spatial.mu))
            temp_rmse_no_spatial.append(mean_squared_error(Y,reg_no_spatial.mu,squared=False))
            temp_similarity_no_spatial.append(cos_similarity(Y,reg_no_spatial.mu))
            temp_crossentropy_no_spatial.append(-(1/n_samples)*np.sum(Y*np.log(reg_no_spatial.mu)))
            
            reg_spatial_ce = dirichlet_regression.dirichletRegressor(spatial=True)
            reg_spatial_ce.fit(X, Y, loss='crossentropy', W=W, fit_intercept=False, verbose=0)
            solutions_ce_spatial_temp.append(np.concatenate([reg_spatial_ce.beta.flatten(),[reg_spatial_ce.rho]]))
            temp_r2_ce_spatial.append(r2_score(Y,reg_spatial_ce.mu))
            temp_rmse_ce_spatial.append(mean_squared_error(Y,reg_spatial_ce.mu,squared=False))
            temp_similarity_ce_spatial.append(cos_similarity(Y,reg_spatial_ce.mu))
            temp_crossentropy_ce_spatial.append(-(1/n_samples)*np.sum(Y*np.log(reg_spatial_ce.mu)))
            
            reg_no_spatial_ce = dirichlet_regression.dirichletRegressor(spatial=False)
            reg_no_spatial_ce.fit(X, Y, loss='crossentropy', fit_intercept=False, verbose=0)
            solutions_ce_no_spatial_temp.append(reg_no_spatial_ce.beta.flatten())
            temp_r2_ce_no_spatial.append(r2_score(Y,reg_no_spatial_ce.mu))
            temp_rmse_ce_no_spatial.append(mean_squared_error(Y,reg_no_spatial_ce.mu,squared=False))
            temp_similarity_ce_no_spatial.append(cos_similarity(Y,reg_no_spatial_ce.mu))
            temp_crossentropy_ce_no_spatial.append(-(1/n_samples)*np.sum(Y*np.log(reg_no_spatial_ce.mu)))
            
        except RuntimeError:
            print("Factor is exactly singular")
        except np.linalg.LinAlgError:
            print("Singular matrix")
        
        seed+=1
    list_solutions_spatial.append(solutions_spatial_temp)
    list_solutions_no_spatial.append(solutions_no_spatial_temp)
    list_solutions_ce_spatial.append(solutions_ce_spatial_temp)
    list_solutions_ce_no_spatial.append(solutions_ce_no_spatial_temp)
    
    list_r2_spatial.append(temp_r2_spatial)
    list_r2_no_spatial.append(temp_r2_no_spatial)
    list_r2_ce_spatial.append(temp_r2_ce_spatial)
    list_r2_ce_no_spatial.append(temp_r2_ce_no_spatial)
    list_rmse_spatial.append(temp_rmse_spatial)
    list_rmse_no_spatial.append(temp_rmse_no_spatial)
    list_rmse_ce_spatial.append(temp_rmse_ce_spatial)
    list_rmse_ce_no_spatial.append(temp_rmse_ce_no_spatial)
    list_crossentropy_spatial.append(temp_crossentropy_spatial)
    list_crossentropy_no_spatial.append(temp_crossentropy_no_spatial)
    list_crossentropy_ce_spatial.append(temp_crossentropy_ce_spatial)
    list_crossentropy_ce_no_spatial.append(temp_crossentropy_ce_no_spatial)
    list_similarity_spatial.append(temp_similarity_spatial)
    list_similarity_no_spatial.append(temp_similarity_no_spatial)
    list_similarity_ce_spatial.append(temp_similarity_ce_spatial)
    list_similarity_ce_no_spatial.append(temp_similarity_ce_no_spatial)

C:\Users\tnguyen001\AppData\Roaming\Python\Python38\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:198: MatrixRankWarning: Matrix is exactly singular
  warn("Matrix is exactly singular", MatrixRankWarning)


Wall time: 26min 15s


In [39]:
print(np.mean(list_similarity_spatial[2]))
print(np.mean(list_similarity_ce_spatial[2]))
print(np.mean(list_similarity_no_spatial[2]))
print(np.mean(list_similarity_ce_no_spatial[2]))

0.9996458716729916
0.9996515560160816
0.9995252281059591
0.9995252284079568


In [40]:
print(np.mean(list_crossentropy_spatial[2]))
print(np.mean(list_crossentropy_ce_spatial[2]))
print(np.mean(list_crossentropy_no_spatial[2]))
print(np.mean(list_crossentropy_ce_no_spatial[2]))

1.0022120233365543
1.0022034740708814
1.0023710892857196
1.0023710800572112


In [15]:
true_params_effective = np.concatenate([beta[:,1:].flatten(),gamma_var, [rho]])
true_params_effective_no_spatial = np.concatenate([beta[:,1:].flatten(),gamma_var])

In [41]:
np.save('Data Dirichlet/solutions_spatial_rho01_multinomial.npy',list_solutions_spatial)
np.save('Data Dirichlet/solutions_no_spatial_rho01_multinomial.npy',list_solutions_no_spatial)
np.save('Data Dirichlet/solutions_ce_spatial_rho01_multinomial.npy',list_solutions_ce_spatial)
np.save('Data Dirichlet/solutions_ce_no_spatial_rho01_multinomial.npy',list_solutions_ce_no_spatial)

In [42]:
np.save('Data Dirichlet/r2_spatial_rho01_multinomial.npy',list_r2_spatial)
np.save('Data Dirichlet/r2_no_spatial_rho01_multinomial.npy',list_r2_no_spatial)
np.save('Data Dirichlet/r2_ce_spatial_rho01_multinomial.npy',list_r2_ce_spatial)
np.save('Data Dirichlet/r2_ce_no_spatial_rho01_multinomial.npy',list_r2_ce_no_spatial)
np.save('Data Dirichlet/rmse_spatial_rho01_multinomial.npy',list_rmse_spatial)
np.save('Data Dirichlet/rmse_no_spatial_rho01_multinomial.npy',list_rmse_no_spatial)
np.save('Data Dirichlet/rmse_ce_spatial_rho01_multinomial.npy',list_rmse_ce_spatial)
np.save('Data Dirichlet/rmse_ce_no_spatial_rho01_multinomial.npy',list_rmse_ce_no_spatial)
np.save('Data Dirichlet/crossentropy_spatial_rho01_multinomial.npy',list_crossentropy_spatial)
np.save('Data Dirichlet/crossentropy_no_spatial_rho01_multinomial.npy',list_crossentropy_no_spatial)
np.save('Data Dirichlet/crossentropy_ce_spatial_rho01_multinomial.npy',list_crossentropy_ce_spatial)
np.save('Data Dirichlet/crossentropy_ce_no_spatial_rho01_multinomial.npy',list_crossentropy_ce_no_spatial)
np.save('Data Dirichlet/similarity_spatial_rho01_multinomial.npy',list_similarity_spatial)
np.save('Data Dirichlet/similarity_no_spatial_rho01_multinomial.npy',list_similarity_no_spatial)
np.save('Data Dirichlet/similarity_ce_spatial_rho01_multinomial.npy',list_similarity_ce_spatial)
np.save('Data Dirichlet/similarity_ce_no_spatial_rho01_multinomial.npy',list_similarity_ce_no_spatial)

In [11]:
list_solutions_spatial = np.load('Data Dirichlet/solutions_spatial_rho01_multinomial.npy')
list_solutions_no_spatial = np.load('Data Dirichlet/solutions_no_spatial_rho01_multinomial.npy')
list_solutions_ce_spatial = np.load('Data Dirichlet/solutions_ce_spatial_rho01_multinomial.npy')
list_solutions_ce_no_spatial = np.load('Data Dirichlet/solutions_ce_no_spatial_rho01_multinomial.npy')

In [16]:
true_params_effective

array([-1.6 ,  1.  ,  1.8 , -1.4 ,  1.4 , -1.1 , -0.05, -0.11,  0.1 ])

In [25]:
np.mean([sol_i[:-2] - true_params_effective_no_spatial[:-2] for sol_i in list_solutions_no_spatial[0]],axis=0)

array([ 0.04112585, -0.05425365, -0.04252704,  0.0409255 , -0.03349975,
        0.03788746])

In [24]:
np.mean([sol_i - true_params_effective_no_spatial[:-2] for sol_i in list_solutions_ce_no_spatial[0]],axis=0)

array([ 0.0416002 , -0.05313316, -0.04251055,  0.04169962, -0.03423354,
        0.03566908])

# rho=0.5

In [95]:
rho=0.5

In [96]:
n_repeat = 10
#list_n_samples = [50,200,1000]
list_n_samples = [50,200]

In [210]:
%%time
list_solutions_spatial = []
list_solutions_no_spatial = []
list_solutions_ce_spatial = []
list_solutions_ce_no_spatial = []
list_solutions_multinomial_spatial = []
list_r2_spatial, list_r2_no_spatial, list_r2_ce_spatial, list_r2_ce_no_spatial, list_r2_multinomial_spatial = [], [], [], [], []
list_rmse_spatial, list_rmse_no_spatial, list_rmse_ce_spatial, list_rmse_ce_no_spatial, list_rmse_multinomial_spatial = [], [], [], [], []
list_crossentropy_spatial, list_crossentropy_no_spatial, list_crossentropy_ce_spatial, list_crossentropy_ce_no_spatial, list_crossentropy_multinomial_spatial = [], [], [], [], []
list_similarity_spatial, list_similarity_no_spatial, list_similarity_ce_spatial, list_similarity_ce_no_spatial, list_similarity_multinomial_spatial = [], [], [], [], []


seed=1

for i in range(len(list_n_samples)):
    n_samples = list_n_samples[i]
    
    true_params = np.concatenate([beta.flatten(),gamma_var, [rho]])
    
    solutions_spatial_temp = []
    solutions_no_spatial_temp = []
    solutions_ce_spatial_temp = []
    solutions_ce_no_spatial_temp = []
    solutions_multinomial_spatial_temp = []
    temp_r2_spatial, temp_r2_no_spatial, temp_r2_ce_spatial, temp_r2_ce_no_spatial, temp_r2_multinomial_spatial = [], [], [], [], []
    temp_rmse_spatial, temp_rmse_no_spatial, temp_rmse_ce_spatial, temp_rmse_ce_no_spatial, temp_rmse_multinomial_spatial = [], [], [], [], []
    temp_crossentropy_spatial, temp_crossentropy_no_spatial, temp_crossentropy_ce_spatial, temp_crossentropy_ce_no_spatial, temp_crossentropy_multinomial_spatial = [], [], [], [], []
    temp_similarity_spatial, temp_similarity_no_spatial, temp_similarity_ce_spatial, temp_similarity_ce_no_spatial, temp_similarity_multinomial_spatial = [], [], [], [], []
    
    #les n_i ne devraient pas bouger, il faut les fixer comme pour les betas
    list_n_i = np.random.randint(1000, high=100000, size=n_samples)
    for _ in range(n_repeat):
        np.random.seed(seed)
        
        X,Z,W = create_features_matrices(n_samples,n_features,choice_W='random_distance',nneighbors=10)
        Z = np.ones(n_samples).reshape(-1,1)
        M = np.identity(n_samples) - rho*W
        mu = dirichlet_regression.compute_mu_spatial(X, beta, M)
        
        Y = np.array([np.random.multinomial(list_n_i[i],mu[i])/list_n_i[i] for i in range(n_samples)])
        Y = (Y*(n_samples-1)+1/n_classes)/n_samples

        try:
            reg_spatial = dirichlet_regression.dirichletRegressor(spatial=True, maxfun=10000)
            reg_spatial.fit(X, Y, parametrization='alternative', Z=Z, W=W, fit_intercept=False, verbose=0)
            solutions_spatial_temp.append(np.concatenate([reg_spatial.beta.flatten(),reg_spatial.gamma,[reg_spatial.rho]]))
            temp_r2_spatial.append(r2_score(Y,reg_spatial.mu))
            temp_rmse_spatial.append(mean_squared_error(Y,reg_spatial.mu,squared=False))
            temp_similarity_spatial.append(cos_similarity(Y,reg_spatial.mu))
            temp_crossentropy_spatial.append(-(1/n_samples)*np.sum(Y*np.log(reg_spatial.mu)))
            
            reg_no_spatial = dirichlet_regression.dirichletRegressor(spatial=False, maxfun=10000)
            reg_no_spatial.fit(X, Y, parametrization='alternative', Z=Z, fit_intercept=False, verbose=0)
            solutions_no_spatial_temp.append(np.concatenate([reg_no_spatial.beta.flatten(),reg_no_spatial.gamma]))
            temp_r2_no_spatial.append(r2_score(Y,reg_no_spatial.mu))
            temp_rmse_no_spatial.append(mean_squared_error(Y,reg_no_spatial.mu,squared=False))
            temp_similarity_no_spatial.append(cos_similarity(Y,reg_no_spatial.mu))
            temp_crossentropy_no_spatial.append(-(1/n_samples)*np.sum(Y*np.log(reg_no_spatial.mu)))
            
            reg_spatial_ce = dirichlet_regression.dirichletRegressor(spatial=True, maxfun=10000)
            reg_spatial_ce.fit(X, Y, loss='crossentropy', W=W, fit_intercept=False, verbose=0)
            solutions_ce_spatial_temp.append(np.concatenate([reg_spatial_ce.beta.flatten(),[reg_spatial_ce.rho]]))
            temp_r2_ce_spatial.append(r2_score(Y,reg_spatial_ce.mu))
            temp_rmse_ce_spatial.append(mean_squared_error(Y,reg_spatial_ce.mu,squared=False))
            temp_similarity_ce_spatial.append(cos_similarity(Y,reg_spatial_ce.mu))
            temp_crossentropy_ce_spatial.append(-(1/n_samples)*np.sum(Y*np.log(reg_spatial_ce.mu)))
            
            reg_no_spatial_ce = dirichlet_regression.dirichletRegressor(spatial=False, maxfun=10000)
            reg_no_spatial_ce.fit(X, Y, loss='crossentropy', fit_intercept=False, verbose=0)
            solutions_ce_no_spatial_temp.append(reg_no_spatial_ce.beta.flatten())
            temp_r2_ce_no_spatial.append(r2_score(Y,reg_no_spatial_ce.mu))
            temp_rmse_ce_no_spatial.append(mean_squared_error(Y,reg_no_spatial_ce.mu,squared=False))
            temp_similarity_ce_no_spatial.append(cos_similarity(Y,reg_no_spatial_ce.mu))
            temp_crossentropy_ce_no_spatial.append(-(1/n_samples)*np.sum(Y*np.log(reg_no_spatial_ce.mu)))
            
            reg_multinomial = dirichlet_regression.dirichletRegressor(spatial=True, maxfun=10000)
            reg_multinomial.fit(X, Y, loss='crossentropy', W=W, fit_intercept=False, verbose=0, size_samples=list_n_i)
            solutions_multinomial_spatial_temp.append(reg_multinomial.beta.flatten())
            temp_r2_multinomial_spatial.append(r2_score(Y,reg_multinomial.mu))
            temp_rmse_multinomial_spatial.append(mean_squared_error(Y,reg_multinomial.mu,squared=False))
            temp_similarity_multinomial_spatial.append(cos_similarity(Y,reg_multinomial.mu))
            temp_crossentropy_multinomial_spatial.append(-(1/n_samples)*np.sum(Y*np.log(reg_multinomial.mu)))
            
        except RuntimeError:
            print("Factor is exactly singular")
        except np.linalg.LinAlgError:
            print("Singular matrix")
        
        seed+=1
    list_solutions_spatial.append(solutions_spatial_temp)
    list_solutions_no_spatial.append(solutions_no_spatial_temp)
    list_solutions_ce_spatial.append(solutions_ce_spatial_temp)
    list_solutions_ce_no_spatial.append(solutions_ce_no_spatial_temp)
    list_solutions_multinomial_spatial.append(solutions_multinomial_spatial_temp)
    
    list_r2_spatial.append(temp_r2_spatial)
    list_r2_no_spatial.append(temp_r2_no_spatial)
    list_r2_ce_spatial.append(temp_r2_ce_spatial)
    list_r2_ce_no_spatial.append(temp_r2_ce_no_spatial)
    list_r2_multinomial_spatial.append(temp_r2_multinomial_spatial)
    list_rmse_spatial.append(temp_rmse_spatial)
    list_rmse_no_spatial.append(temp_rmse_no_spatial)
    list_rmse_ce_spatial.append(temp_rmse_ce_spatial)
    list_rmse_ce_no_spatial.append(temp_rmse_ce_no_spatial)
    list_rmse_multinomial_spatial.append(temp_rmse_multinomial_spatial)
    list_crossentropy_spatial.append(temp_crossentropy_spatial)
    list_crossentropy_no_spatial.append(temp_crossentropy_no_spatial)
    list_crossentropy_ce_spatial.append(temp_crossentropy_ce_spatial)
    list_crossentropy_ce_no_spatial.append(temp_crossentropy_ce_no_spatial)
    list_crossentropy_multinomial_spatial.append(temp_crossentropy_multinomial_spatial)
    list_similarity_spatial.append(temp_similarity_spatial)
    list_similarity_no_spatial.append(temp_similarity_no_spatial)
    list_similarity_ce_spatial.append(temp_similarity_ce_spatial)
    list_similarity_ce_no_spatial.append(temp_similarity_ce_no_spatial)
    list_similarity_multinomial_spatial.append(temp_similarity_multinomial_spatial)

C:\Users\tnguyen001\AppData\Roaming\Python\Python38\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:198: MatrixRankWarning: Matrix is exactly singular
  warn("Matrix is exactly singular", MatrixRankWarning)


Wall time: 2min 50s


In [211]:
print(np.mean(list_similarity_spatial[1]))
print(np.mean(list_similarity_ce_spatial[1]))
print(np.mean(list_similarity_multinomial_spatial[1]))

0.9999651597177928
0.9999409857089283
0.9999382392351275


In [212]:
print(np.mean(list_crossentropy_spatial[1]))
print(np.mean(list_crossentropy_ce_spatial[1]))
print(np.mean(list_crossentropy_multinomial_spatial[1]))

0.4557490893521389
0.4557247983441735
0.45572840388428626


In [213]:
print(np.mean(list_r2_spatial[1]))
print(np.mean(list_r2_ce_spatial[1]))
print(np.mean(list_r2_multinomial_spatial[1]))

0.9995520274054134
0.9992383342699215
0.999199432865167
